apiVersion: v1
kind: Pod
metadata:
  name: kuard-health
  namespace: test
  labels:
    mark: kuard-health
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard-health
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        port: 8080
        path: /
      initialDelaySeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3


