apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuard-nfs-pvc01
  namespace: test
#  labels:
#    storage_method: PersistentVolumeClaim
#    Filesystem: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "kuard-slow"
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard-volume-pvc
  namespace: test
  labels:
    mark: kuard-volume-pvc
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard-nfs-pvc
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: kuard-pvc-data
      mountPath: /gjkdhr
  volumes:
  - name: kuard-pvc-data
    persistentVolumeClaim:
      claimName: kuard-nfs-pvc01

