apiVersion: v1
kind: PersistentVolume
metadata: 
  name: kuard-pv001
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/k8s_data/pv001
    server: 192.168.110.31
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: kuard-pvc001
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
