apiVersion: v1          #主要目的是使用Service的NodePort给k8s集群中Service映射一个外网可以访问的端口。
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  type: NodePort        #表示使用Node上的物理端口提供对外访问的能力。
  ports:
  - port: 80
    nodePort: 31110     #映射到容器Service提供服务的IP的80端口。需要注意的是,spec.ports.nodePort的端口定义有范围限制，默认在30000-32767之间。
  selector:
    name: frontend
