apiVersion: v1
kind: Pod
metadata:
  name: kuard-nfs-volume
  namespace: test
  labels:
    mark: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard-nfs-volume
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: kuard-nfs-volume
      mountPath: /gjkdhr
      readOnly: false
  volumes:
  - name: kuard-nfs-volume
    nfs:
      path: /data/k8s_data
      readOnly: false
      server: 192.168.110.31


