apiVersion: v1
kind: Pod
metadata:
  name: kuard-reslim
  namespace: test
  labels:
    mark: kuard-reslim
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard-reslim
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"
