apiVersion: v1
kind: Pod
metadata:
  name: kuard
  namespace: test
  labels:
    mark: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
