apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume
  namespace: test
  labels:
    mark: nginx-volume
spec:
  containers:
  - image: nginx:latest
    name: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
  volumes:
  - name: "nginx-data"
    hostPath:
      path: "/mnt/nginx_volume_test/" 
      type: Directory
