apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-mount
  namespace: test
  labels:
    app: myapp
    tier: frontend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: nginx-conf          #匹配volume存储名
      mountPath: /etc/nginx/conf.d/
  volumes:
  - name: nginx-conf 
    configMap:
      defaultMode: 0644
      name: nginx-www      #与namespace空间下的configMap资源对应
  
