apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-test
  namespace: test
data:
  server_name: myapp.magedu.com
  nginx_port: 80


#create configmap use env
#[root@Master-K8S-Test configmap]# kubectl create configmap nginx-config --from-literal=server_name=myapp.magedu.com --from-literal=nginx_port=80 --namespace=test
#configmap/nginx-config created


#create configmap use file
#[root@Master-K8S-Test configmap]# kubectl create configmap nginx-www --from-file=./www.conf --namespace=test
#configmap/nginx-www created
